name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test Repo
      id: test-repo
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Repo
        setup-command: ''
        command: "./tests/run.sh"
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-REPO_RESULTS: "${{steps.test-repo.outputs.result}}"
      with:
        runners: test-repo
